#!/bin/bash

#
# Converts coordinates generated by 
# http://turin.nss.udel.edu/research/tubegenonline.html
# input <x,y,z> pairs and strips headers.
#

# Check if input and output file specified
if [ $# -le 1 ]; then
    echo "No arguments supplied!"
    echo "Usage: ./convert_cnt_coords.sh <input.txt> <output.txt> (optional:skip-n)"
    echo "         skip-n: default = 6"
    exit 1
fi

# Check if input file exists
if [ ! -f $1 ]; then
    echo "Input file not found!"
    exit 1
fi

skiplines=6;

# Skip non-default number of lines of header (rarely used)
if [ $# -eq 3 ]; then
    skiplines=$3
fi

echo "Converting $1 into <x,y,z> pairs, skipping first $skiplines."
awk -v skiplines="$skiplines" 'NR>skiplines { print $2 " " $3 " " $4}' $1 > $2

# Check return value of command
if [ $? -eq 0 ]; then
    echo "Conversion successful."
else
    echo "Errors occured, check output file."
fi
